### ISSUE TITLE
Simplify use of regular expressions

### ISSUE THREAD

**Issue by amitguptagwl** [NaturalIntelligence/anumargak#3]
This is how the dynamic route is added currently;

```js
router.on("GET", "/this/is/:dynamic/with/:pattern(\\d+)", handler);
```

We are planning to name regular expressions used for path parameters
```js
router.addNamedExpression("num","\\d+");
router.on("GET", "/this/is/:dynamic/with/:pattern(:num:)", handler); //valid
//router.on("GET", "/this/is/:dynamic/with/:pattern(\\d+)", handler); //valid
```

Named expression can be added in following two ways

```js
router.addNamedExpression("num","\\d+");
router.addNamedExpressions({
   "name1" : "regx1",
   "name2" : "regx2",
});
```

Named expressions will be replaced at the time of adding the route. So it should not impact application performance.

**Comment by shuklajay117** [comment]
I'm working on it

**Comment by amitguptagwl** [comment]
I hope you're clear with the motive behind this issue. Feel free to clear any doubt

**Comment by shuklajay117** [comment]
My understanding is as below: 

It should support of adding regular expression using `addNameExpression` method. We will keep track of all regex into a map. Once user have defined some re-usable regex to it, they are able to use it using `:regexKeyName:` in url. We need to make sure this name should get replaced with specified regex pattern before it gets registered. I assume that there can be multiple dynamic regex keys used in a url so we need to replace all of them.

Please correct me if anything wrong!

**Comment by amitguptagwl** [comment]
You're right.
