### ISSUE TITLE
Rename this project

### ISSUE THREAD

**Issue by amitguptagwl** [NaturalIntelligence/anumargak#4]
It is suggested that the name of this repository is a bit difficult to pronounce, hence difficult to remember. So we're planning to rename it something short and meaningful; Please suggest some good name;

1. Name should not have more than 3 consonants
2. It is recommended if it's meaning is related to navigator, or router.
3. It is recommended if it is derived from Hindi or Sanskrit language.

Some suggestions are
* 'Pathak'
* 'Anuma'
* 'Margak'

**Comment by rajeshdh** [comment]
I like Pathak.

**Comment by amitguptagwl** [comment]
Thanks. I'm just thinking do people really want to use this router? They'll have to make their own web server for that as existing web server frameworks don't let you use custom router. 

I think Muneem is only the web framework who is gonna use it. So may be keep it as it is.
