### ISSUE TITLE
ignoreLeadingSlash

### ISSUE THREAD

**Issue by amitguptagwl** [NaturalIntelligence/anumargak#5]
Many people do mistakes mapping the URL. Hence we want to introduce `ignoreLeadingSlash` with default `true` value. So that if user forget to miss using leading slash this application automatically adds it.

**Comment by shuklajay117** [comment]
@amitguptagwl I can help you in this.

**Comment by amitguptagwl** [comment]
Thanks @shuklajay117 . Let me know if you need any guidance to get this issue solved.

**Comment by shuklajay117** [comment]
Sure @amitguptagwl

**Comment by amitguptagwl** [comment]
fixed
